# Generated by Django 6.0.4 on 2026-04-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('publico', 'Público'), ('privado', 'Privado'), ('clinica', 'Clínica'), ('centro_salud', 'Centro de Salud')], max_length=20)),
                ('nombre', models.CharField(max_length=200)),
                ('alias', models.CharField(blank=True, max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('contacto', models.CharField(max_length=50)),
                ('especialidad', models.CharField(max_length=200)),
                ('ubicacion', models.CharField(max_length=300)),
                ('periodo', models.CharField(help_text='Ej: Lun-Vie 8am-6pm', max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hospital',
                'verbose_name_plural': 'Hospitales',
                'ordering': ['nombre'],
            },
        ),
    ]
