# Generated by Django 6.0.6 on 2026-06-21 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='fecha_desactivacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='motivo_desactivacion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
