# Generated by Django 6.0.6 on 2026-07-05 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente_id', models.IntegerField()),
                ('paciente_nombre', models.CharField(blank=True, max_length=255)),
                ('cita_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('despacho_id', models.IntegerField(blank=True, null=True)),
                ('monto_consulta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monto_medicamentos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monto_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('pagada', models.BooleanField(default=False)),
                ('metodo_pago', models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia')], max_length=20)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-fecha_emision'],
            },
        ),
    ]
