# Generated by Django 6.0.4 on 2026-05-03 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facturacion', '0001_initial'),
        ('historial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturacion',
            name='receta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='historial.receta'),
        ),
    ]
