# Generated by Django 5.2.16 on 2026-07-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente_id', models.IntegerField(verbose_name='ID del paciente en Auth Service')),
                ('paciente_nombre', models.CharField(max_length=255)),
                ('medico_id', models.IntegerField(blank=True, null=True, verbose_name='ID del médico en Médicos Service')),
                ('medico_nombre', models.CharField(blank=True, max_length=255)),
                ('contenido', models.TextField()),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('leido', models.BooleanField(default=False)),
                ('enviado_por', models.CharField(choices=[('paciente', 'Paciente'), ('medico', 'Médico'), ('sistema', 'Sistema')], default='paciente', max_length=10)),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
