# Generated by Django 6.0.4 on 2026-04-20 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('funcion', models.TextField()),
                ('tipo', models.CharField(choices=[('analgesico', 'Analgésico'), ('antibiotico', 'Antibiótico'), ('antiinflamatorio', 'Antiinflamatorio'), ('antiviral', 'Antiviral'), ('vitamina', 'Vitamina'), ('otro', 'Otro')], max_length=30)),
                ('stock', models.IntegerField(default=0)),
                ('descripcion', models.TextField(blank=True)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to='hospitales.hospital')),
            ],
            options={
                'verbose_name': 'Medicamento',
                'verbose_name_plural': 'Medicamentos',
                'ordering': ['nombre'],
            },
        ),
    ]
