# Generated by Django 6.0.5 on 2026-05-24 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_initial'),
        ('medicamentos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_despacho', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, help_text='Total del despacho basado en el costo de los medicamentos', max_digits=10)),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='despacho', to='citas.cita')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despachos', to='usuarios.medico')),
            ],
            options={
                'verbose_name': 'Despacho',
                'verbose_name_plural': 'Despachos',
                'ordering': ['-fecha_despacho'],
            },
        ),
        migrations.CreateModel(
            name='DespachoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('despacho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='medicamentos.despacho')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medicamentos.medicamento')),
            ],
            options={
                'verbose_name': 'Ítem de Despacho',
                'verbose_name_plural': 'Ítems de Despacho',
            },
        ),
    ]
