# Generated by Django 6.0.4 on 2026-04-20 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('leido', models.BooleanField(default=False)),
                ('enviado_por', models.CharField(choices=[('paciente', 'Paciente'), ('medico', 'Médico'), ('sistema', 'Sistema')], default='paciente', max_length=10)),
                ('medico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes', to='usuarios.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='usuarios.paciente')),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'ordering': ['fecha_hora'],
            },
        ),
    ]
