# Generated by Django 6.0.4 on 2026-07-05 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True, verbose_name='ID en Auth Service')),
                ('nombre', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('especialidad', models.CharField(choices=[('Cardiologia', 'Cardiología'), ('Pediatria', 'Pediatría'), ('Ginecologia', 'Ginecología'), ('Neurologia', 'Neurología'), ('Traumatologia', 'Traumatología'), ('Dermatologia', 'Dermatología'), ('Medicina General', 'Medicina General'), ('Psiquiatria', 'Psiquiatría'), ('Oftalmologia', 'Oftalmología'), ('Otorrinolaringologia', 'Otorrinolaringología')], max_length=50)),
                ('ubicacion', models.CharField(max_length=100)),
                ('servicio_sanitario', models.CharField(max_length=100)),
                ('hospital_id', models.IntegerField(blank=True, null=True, verbose_name='ID del hospital')),
                ('disponibilidad', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Médico',
                'verbose_name_plural': 'Médicos',
            },
        ),
    ]
