# Generated by Django 6.0.6 on 2026-07-07 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('publico', 'Público'), ('privado', 'Privado'), ('clinica', 'Clínica'), ('centro_salud', 'Centro de Salud')], default='publico', max_length=20)),
                ('nombre', models.CharField(max_length=255)),
                ('alias', models.CharField(blank=True, max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('contacto', models.CharField(max_length=20)),
                ('especialidad', models.CharField(max_length=255)),
                ('ubicacion', models.CharField(max_length=255)),
                ('periodo', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('fecha_desactivacion', models.DateTimeField(blank=True, null=True)),
                ('motivo_desactivacion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Hospital',
                'verbose_name_plural': 'Hospitales',
                'ordering': ['-creado_en'],
            },
        ),
    ]
