# Generated by Django 5.2.16 on 2026-07-09 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente_id', models.IntegerField()),
                ('paciente_nombre', models.CharField(blank=True, max_length=255)),
                ('medico_nombre', models.CharField(blank=True, max_length=255)),
                ('especialidad', models.CharField(blank=True, max_length=100)),
                ('tipo', models.CharField(blank=True, max_length=50)),
                ('inicio', models.DateTimeField()),
                ('fin', models.DateTimeField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('en_curso', 'En curso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=10)),
                ('motivo', models.TextField(blank=True)),
                ('nota', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['-inicio'],
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('publico', 'Público'), ('privado', 'Privado'), ('clinica', 'Clínica'), ('centro_salud', 'Centro de Salud')], default='publico', max_length=20)),
                ('nombre', models.CharField(max_length=255)),
                ('alias', models.CharField(blank=True, max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('contacto', models.CharField(max_length=20)),
                ('especialidad', models.CharField(max_length=255)),
                ('ubicacion', models.CharField(max_length=255)),
                ('periodo', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('fecha_desactivacion', models.DateTimeField(blank=True, null=True)),
                ('motivo_desactivacion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Hospital',
                'verbose_name_plural': 'Hospitales',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente_id', models.IntegerField()),
                ('paciente_nombre', models.CharField(blank=True, max_length=255)),
                ('receta_id', models.IntegerField(blank=True, null=True)),
                ('monto_consulta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monto_medicamentos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField(blank=True)),
                ('pagada', models.BooleanField(default=False)),
                ('metodo_pago', models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia')], max_length=20)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('cita', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='factura', to='citas.cita')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True, verbose_name='ID en Auth Service')),
                ('nombre', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('especialidad', models.CharField(choices=[('Cardiologia', 'Cardiología'), ('Pediatria', 'Pediatría'), ('Ginecologia', 'Ginecología'), ('Neurologia', 'Neurología'), ('Traumatologia', 'Traumatología'), ('Dermatologia', 'Dermatología'), ('Medicina General', 'Medicina General'), ('Psiquiatria', 'Psiquiatría'), ('Oftalmologia', 'Oftalmología'), ('Otorrinolaringologia', 'Otorrinolaringología')], max_length=50)),
                ('ubicacion', models.CharField(max_length=100)),
                ('servicio_sanitario', models.CharField(max_length=100)),
                ('disponibilidad', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='citas.hospital', verbose_name='Hospital')),
            ],
            options={
                'verbose_name': 'Médico',
                'verbose_name_plural': 'Médicos',
            },
        ),
        migrations.AddField(
            model_name='cita',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='citas.medico'),
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente_id', models.IntegerField()),
                ('paciente_nombre', models.CharField(blank=True, max_length=255)),
                ('contenido', models.TextField()),
                ('enviado_por', models.CharField(choices=[('paciente', 'Paciente'), ('medico', 'Médico'), ('sistema', 'Sistema')], max_length=10)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('leido', models.BooleanField(default=False)),
                ('medico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes', to='citas.medico')),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'ordering': ['fecha_hora'],
            },
        ),
    ]
