apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: red-hospital
type: Opaque
stringData:
  POSTGRES_PASSWORD: postgres
  MYSQL_ROOT_PASSWORD: root
  MSSQL_SA_PASSWORD: "YourPassword123!"
  JWT_SECRET: "django-insecure-dev-key-change-in-production"
