server:
  port: 8001
  name: auth-service

database:
  engine: django.db.backends.postgresql
  name: db_auth
  user: postgres
  password: postgres
  host: postgres-auth
  port: 5432

jwt:
  secret: clave-super-segura-cambiar-en-produccion
  algorithm: HS256
  expiration_minutes: 60

consul:
  host: consul
  port: 8500
