server:
  port: 8003
  name: citas-service

database:
  engine: mssql
  name: db_citas
  user: sa
  password: YourPassword123!
  host: mssql-citas
  port: 1433

services:
  auth: "http://auth-service:8001"
  pacientes: "http://pacientes-service:8002"
  medicamentos: "http://medicamentos-service:8005"

consul:
  host: consul
  port: 8500
