server:
  port: 8003
  name: medicos-service

database:
  engine: django.db.backends.postgresql
  name: db_medicos
  user: postgres
  password: postgres
  host: localhost
  port: 5432

services:
  auth: "http://localhost:8001"

consul:
  host: localhost
  port: 8500
