server:
  port: 8005
  name: medicamentos-service

database:
  engine: django.db.backends.postgresql
  name: db_medicamentos
  user: postgres
  password: postgres
  host: postgres-medicamentos
  port: 5432

services:
  auth: "http://auth-service:8001"
  medicos: "http://medicos-service:8003"

consul:
  host: consul
  port: 8500
