server:
  port: 8002
  name: pacientes-service

database:
  engine: django.db.backends.postgresql
  name: db_pacientes
  user: postgres
  password: postgres
  host: localhost
  port: 5433

services:
  auth: "http://localhost:8001"

consul:
  host: localhost
  port: 8500
