server:
  port: 8002
  name: pacientes-service

database:
  engine: django.db.backends.mysql
  name: db_pacientes
  user: root
  password: root
  host: mysql-pacientes
  port: 3306

services:
  auth: "http://auth-service:8001"

consul:
  host: consul
  port: 8500
