server:
  port: 8007
  name: soporte-service

database:
  engine: django.db.backends.postgresql
  name: db_soporte
  user: postgres
  password: postgres
  host: localhost
  port: 5432

services:
  auth: "http://auth-service:8001"

consul:
  host: consul
  port: 8500
