# Generated by Django 5.2.16 on 2026-07-07 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('compartir_red', models.BooleanField(default=False)),
                ('investigacion', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Historial médico',
                'verbose_name_plural': 'Historiales médicos',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('laboratorio', 'Laboratorio'), ('imagen', 'Imagen'), ('clinico', 'Clínico'), ('otro', 'Otro')], max_length=20)),
                ('duracion', models.IntegerField(help_text='Duración en minutos')),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('nota', models.TextField(blank=True)),
                ('historial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes', to='pacientes.historial')),
            ],
            options={
                'verbose_name': 'Examen',
                'ordering': ['-fecha', '-hora'],
            },
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_clinico', models.CharField(max_length=200)),
                ('categoria', models.CharField(max_length=100)),
                ('severidad', models.CharField(choices=[('leve', 'Leve'), ('moderado', 'Moderado'), ('grave', 'Grave'), ('critico', 'Crítico')], max_length=15)),
                ('ubicacion_anatomica', models.CharField(max_length=150)),
                ('fecha_hora_inicio', models.DateTimeField()),
                ('edad_inicio', models.IntegerField()),
                ('descripcion_inicio', models.TextField()),
                ('fecha_hora_reduccion', models.DateTimeField(blank=True, null=True)),
                ('edad_reduccion', models.IntegerField(blank=True, null=True)),
                ('descripcion_reduccion', models.TextField(blank=True)),
                ('nota', models.TextField(blank=True)),
                ('historial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos', to='pacientes.historial')),
            ],
            options={
                'verbose_name': 'Diagnóstico',
                'verbose_name_plural': 'Diagnósticos',
                'ordering': ['-fecha_hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Observacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_consulta', models.TextField()),
                ('antecedentes_patologicos', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('historial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='pacientes.historial')),
            ],
            options={
                'verbose_name': 'Observación',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='historial',
            name='paciente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='pacientes.paciente'),
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento_id', models.IntegerField(help_text='ID del medicamento en medicamentos-service')),
                ('intencion', models.TextField()),
                ('categoria', models.CharField(choices=[('controlado', 'Controlado'), ('libre', 'Libre venta'), ('retenida', 'Retenida')], max_length=20)),
                ('prioridad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], max_length=10)),
                ('instruccion_dosis', models.TextField()),
                ('periodo_dosis', models.CharField(help_text='Ej: Cada 8 horas por 7 días', max_length=100)),
                ('cantidad_suministrada', models.IntegerField()),
                ('fecha_emitida', models.DateTimeField(auto_now_add=True)),
                ('historial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='pacientes.historial')),
            ],
            options={
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Recetas',
                'ordering': ['-fecha_emitida'],
            },
        ),
    ]
