# Generated by Django 5.2.16 on 2026-07-07 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medico_id', models.IntegerField(verbose_name='ID del médico')),
                ('medico_nombre', models.CharField(blank=True, max_length=255)),
                ('paciente_id', models.IntegerField(default=0, verbose_name='ID del paciente')),
                ('paciente_nombre', models.CharField(blank=True, max_length=255)),
                ('cita_id', models.IntegerField(unique=True, verbose_name='ID de la cita')),
                ('fecha_despacho', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Despacho',
                'verbose_name_plural': 'Despachos',
                'ordering': ['-fecha_despacho'],
            },
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_id', models.IntegerField(verbose_name='ID del hospital')),
                ('nombre', models.CharField(max_length=200)),
                ('funcion', models.TextField()),
                ('tipo', models.CharField(choices=[('analgesico', 'Analgésico'), ('antibiotico', 'Antibiótico'), ('antiinflamatorio', 'Antiinflamatorio'), ('antiviral', 'Antiviral'), ('vitamina', 'Vitamina'), ('otro', 'Otro')], max_length=30)),
                ('stock', models.IntegerField(default=0)),
                ('descripcion', models.TextField(blank=True)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Medicamento',
                'verbose_name_plural': 'Medicamentos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='DespachoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento_id', models.IntegerField(verbose_name='ID del medicamento')),
                ('medicamento_nombre', models.CharField(blank=True, max_length=200)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('despacho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='medicamentos.despacho')),
            ],
            options={
                'verbose_name': 'Ítem de Despacho',
                'verbose_name_plural': 'Ítems de Despacho',
            },
        ),
    ]
