# Generated by Django 6.0.4 on 2026-07-06 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='despacho',
            name='paciente_id',
            field=models.IntegerField(default=0, verbose_name='ID del paciente'),
        ),
        migrations.AddField(
            model_name='despacho',
            name='paciente_nombre',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
