# Generated by Django 6.0.6 on 2026-07-07 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='usuario',
            name='notificaciones',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
