# Generated by Django 6.0.4 on 2026-05-03 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('historial', '0001_initial'),
        ('medicamentos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial',
            name='paciente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='usuarios.paciente'),
        ),
        migrations.AddField(
            model_name='examen',
            name='historial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes', to='historial.historial'),
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='historial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos', to='historial.historial'),
        ),
        migrations.AddField(
            model_name='observacion',
            name='historial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='historial.historial'),
        ),
        migrations.AddField(
            model_name='receta',
            name='historial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='historial.historial'),
        ),
        migrations.AddField(
            model_name='receta',
            name='medicamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recetas', to='medicamentos.medicamento'),
        ),
    ]
