# Generated by Django 6.0.4 on 2026-06-30 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial',
            name='compartir_red',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historial',
            name='investigacion',
            field=models.BooleanField(default=False),
        ),
    ]
