# Generated by Django 6.0.4 on 2026-04-20 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('telecom', models.CharField(max_length=20)),
                ('genero', models.CharField(max_length=10)),
                ('fec_nac', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('tiempo_servicio_inicio', models.DateTimeField(blank=True, null=True)),
                ('tiempo_servicio_fin', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('usuarios.usuario',),
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('fallecido', models.BooleanField(default=False)),
                ('fecha_hora_fallecido', models.DateTimeField(blank=True, null=True)),
                ('direccion', models.CharField(max_length=200)),
                ('estado_civil', models.CharField(max_length=20)),
                ('nac_multiple', models.IntegerField(default=1)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='')),
                ('contacto_nombre', models.CharField(max_length=100)),
                ('contacto_numero', models.CharField(max_length=20)),
                ('contacto_dir', models.CharField(max_length=200)),
                ('idioma_preferido', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
            bases=('usuarios.usuario',),
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('periodo', models.CharField(max_length=50)),
                ('especialidad', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=100)),
                ('servicio_sanitario', models.CharField(max_length=100)),
                ('disponibilidad', models.BooleanField(default=True)),
                ('hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospitales.hospital')),
            ],
            options={
                'abstract': False,
            },
            bases=('usuarios.usuario',),
        ),
    ]
