# Generated by Django 5.2.15 on 2026-07-04 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/'),
        ),
        migrations.CreateModel(
            name='NotificacionPreferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alerta_stock_bajo', models.BooleanField(default=True)),
                ('reportes_automaticos', models.BooleanField(default=True)),
                ('aprobacion_usuarios', models.BooleanField(default=True)),
                ('alertas_email', models.BooleanField(default=False)),
                ('recordatorio_citas', models.BooleanField(default=True)),
                ('resultados_historial', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notif_prefs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
